displayName: X-Request-ID-UUIDV7
type: middleware

import: github.com/METADEVS-GMBH/traefik-plugin-request-id-uuidv7

summary: 'Injects X-Request-ID header with a UUIDv7 value into HTTP requests and responses.'

testData:
  HeaderName: "X-Request-ID"
  Enabled: true
